<template>
  <q-page padding>
    <div class="q-gutter-sm row" style="width: 75%;">
      <div class="world-map map-size night-sky" style="position: absolute;">   </div> 
      <!-- Image Map Generated by http://www.image-map.net/ -->
      <div class="world-map map-size col-xs-12 col-sm-12 col-md-10 col-lg-10">

        <img src="/statics/backgrounds/nightSky-stars.png" usemap="#image-map" style="margin-top: 0%;  position: absolute;">

        <map name="image-map" style="margin-top: 0%;  position: absolute;">
          <area @mouseover="wish1 = true" @mouseleave="wish1 = false" title="wish1" coords="52,234,116,175" shape="rect">
          <area @mouseover="wish2 = true" @mouseleave="wish2 = false" title="wish2" coords="157,15,230,83" shape="rect">
          <area @mouseover="wish3 = true" @mouseleave="wish3 = false" title="wish3" coords="193,437,252,488" shape="rect">
          <area @mouseover="wish4 = true" @mouseleave="wish4 = false" title="wish4" coords="254,758,196,705" shape="rect">
          <area @mouseover="wish5 = true" @mouseleave="wish5 = false" title="wish5" coords="388,983,445,1041" shape="rect">
          <area @mouseover="wish6 = true" @mouseleave="wish6 = false" title="wish6" coords="589,570,650,637" shape="rect">
          <area @mouseover="wish7 = true" @mouseleave="wish7 = false" title="wish7" coords="617,100,689,170" shape="rect">
          <area @mouseover="wish8 = true" @mouseleave="wish8 = false" title="wish8" coords="803,758,859,812" shape="rect">
          <area @mouseover="wish9 = true" @mouseleave="wish9 = false" title="wish9" coords="891,320,957,392" shape="rect">
          <area @mouseover="wish10 = true" @mouseleave="wish10 = false" title="wish10" coords="1217,49,1280,109" shape="rect">
          <area @mouseover="wish11 = true" @mouseleave="wish11 = false" title="wish11" coords="1195,637,1254,693" shape="rect">
          <area @mouseover="wish12 = true" @mouseleave="wish12 = false" title="wish12" coords="1370,980,1439,1060" shape="rect">
          <area @mouseover="wish13 = true" @mouseleave="wish13 = false" title="wish13" coords="1514,398,1565,456" shape="rect">
          <area @mouseover="wish14 = true" @mouseleave="wish14 = false" title="wish14" coords="1738,615,1797,675" shape="rect">
          <area @mouseover="wish15 = true" @mouseleave="wish15 = false" title="wish15" coords="1705,58,1773,124" shape="rect">
          <area @mouseover="wish16 = true" @mouseleave="wish16 = false" title="wish16" coords="1782,816,1839,877" shape="rect">
      </map>

      </div>

      <div class="center">        
        <q-chat-message
          v-show="wish1 || wish4 || wish9 || wish16"
          name="someone is wishing..."        
          :text="['randomized wish text']"
          size="3"          
          text-color="secondary"
          bg-color="white"
        />
        <q-chat-message
          v-show="wish2 || wish6 || wish11 || wish15"
          name="someone is wishing..."        
          :text="['a different wish']"
          size="3"
          sent
          text-color="primary"
          bg-color="white"
        />
        <q-chat-message
          v-show="wish3 || wish5 || wish14 || wish13"
          name="someone is wishing..."        
          :text="['another wish']"
          size="3"
          sent
          text-color="secondry"
          bg-color="white"
        />
        <q-chat-message
          v-show="wish7 || wish8 || wish10 || wish12"
          name="someone is wishing..."        
          :text="['wiisssshhh']"
          size="3"
          text-color="primary"
          bg-color="white"
        />        
      </div>
  
    </div>

  </q-page>
</template>

<script>
import { mapGetters} from "vuex";

export default {

  data() {
    return {
      wish1: false,
      wish2: false,
      wish3: false,
      wish4: false,
      wish5: false,
      wish6: false,
      wish7: false,
      wish8: false,
      wish9: false,
      wish10: false,
      wish11: false,
      wish12: false,
      wish13: false,
      wish14: false,
      wish15: false,
      wish16: false,
    };
  },
  computed: {
    ...mapGetters("settings", ["darkMode"])
  },
}
</script>